# docker-compose.dev.yml
version: "3"
services:
  frontend:
    build:
      context: ./logvis-frontend # Make sure this matches your monorepo structure
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./logvis-frontend
        target: /app
      - type: volume
        source: frontend_node_modules
        target: /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./logvis-backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./logvis-backend
        target: /app
      - type: volume
        source: backend_node_modules
        target: /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  frontend_node_modules:
  backend_node_modules:
