name: Trigger Deploy

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get commit info
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          COMMIT_HASH=$(git log -1 --pretty=%h)

          echo "::set-output name=COMMIT_MSG::$(echo "$COMMIT_MSG" | jq -Rs .)"
          echo "::set-output name=COMMIT_AUTHOR::$COMMIT_AUTHOR"
          echo "::set-output name=COMMIT_HASH::$COMMIT_HASH"

      - name: Trigger deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: jakubs-01/logvis-deploy
          event-type: backend-push
          client-payload: |
            {
              "repository": "backend",
              "commit": "${{ steps.commit.outputs.COMMIT_HASH }}",
              "author": "${{ steps.commit.outputs.COMMIT_AUTHOR }}",
              "message": ${{ steps.commit.outputs.COMMIT_MSG }}
            }
