name: Trigger Deploy

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get commit info
        id: commit
        run: |
          echo "COMMIT_MSG=$(git log -1 --pretty=%B | sed 's/"/\"/g' | tr '\n' ' ')" >> "$GITHUB_ENV"
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> "$GITHUB_ENV"
          echo "COMMIT_HASH=$(git log -1 --pretty=%h)" >> "$GITHUB_ENV"

      - name: Trigger deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: jakubs-01/logvis-deploy
          event-type: backend-push
          client-payload: |
            {
              "repository": "backend",
              "commit": "${{ env.COMMIT_HASH }}",
              "author": "${{ env.COMMIT_AUTHOR }}",
              "message": "${{ env.COMMIT_MSG }}"
            }
