name: deploy

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit info
        run: |
          echo "COMMIT_MSG=$(git log -1 --pretty=%B | sed 's/"/\"/g' | tr '\n' ' ')" >> "$GITHUB_ENV"
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=%an)" >> "$GITHUB_ENV"
          echo "COMMIT_HASH=$(git log -1 --pretty=%h)" >> "$GITHUB_ENV"

      - name: Start Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "🚀 Deployment Started"
          description: "Starting deployment process"
          color: 0xffff00

      - name: Deploy to Server
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 5847
          script: |
            set -e
            echo "Starting deployment..."

            # Navigate to project directory
            cd /home/jakubapp-dev/LogVis

            # Update frontend
            cd logvis-frontend
            git pull origin main

            # Update backend
            cd ../logvis-backend
            git pull origin main

            # Return to root and rebuild
            cd ..
            docker-compose down
            docker-compose up -d --build --remove-orphans

            # Cleanup
            docker image prune -f

      - name: Success Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "✅ Deployment Successful"
          description: |
            Successfully deployed changes!
            Commit: ${{ env.COMMIT_HASH }}
            Author: ${{ env.COMMIT_AUTHOR }}
          color: 0x00ff00

      - name: Failure Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ Deployment Failed"
          description: |
            Failed to deploy changes
            [View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          color: 0xff0000
